# Generated by Django 5.2.10 on 2026-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycoupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent (%)'), ('fixed', 'Fixed (€)'), ('free_delivery', 'Free Delivery')], default='percent', max_length=16),
        ),
    ]
