# Generated by Django 5.2.10 on 2026-02-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_deliveryorder_deliveryorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent (%)'), ('fixed', 'Fixed (€)')], default='percent', max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='deliveryorderitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='deliveryorderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
