# Generated by Django 5.2.10 on 2026-02-14 10:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
