# Generated by Django 5.2.10 on 2026-02-19 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_deliveryorder_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycoupon',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_delivery_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverycoupon',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverycoupon',
            name='issued_month',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
