# Generated by Django 5.2.10 on 2026-02-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_deliverycoupon_assigned_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=40)),
                ('chat_id', models.CharField(blank=True, max_length=50)),
                ('message_preview', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
