# Generated by Django 5.2.10 on 2026-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_addongroup_deliverypricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='telegram_last_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='telegram_last_action_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='telegram_last_status_sent',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]